name: test-app
namespace: kube-system
port: 10301
portName: metrics

replicas: 1

image:
  registry: quay.io
  repository: giantswarm/kube-state-metrics
  tag: v1.8.0

resources:
  limits:
    cpu: 100m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 300Mi

test:
  image:
    registry: quay.io
    repository: giantswarm/alpine-testing
    tag: 0.1.1
