version: 2.1
orbs:
  architect: giantswarm/architect@2.1.0

workflows:
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: push-chart-operator-to-app-catalog
          app_catalog: "sample-catalog"
          app_catalog_test: "sample-catalog"
          chart: "kubernetes-test-app-chart"
          filters:
            # Needed to trigger job also on git tag.
            tags:
              only: /^v.*/
